POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "user1",
  "password": "1234"
}

###

DELETE http://localhost:4000/users?id=2804yshjd
Authorization: 57dyxx7ec7v

###

GET http://localhost:4000/users?id=2804yshjd
Authorization: 9x753iqkwg

###

GET http://localhost:4000/users?name=J
Authorization: xzyscoortra

###

PUT http://localhost:4000/users
Authorization: 9x753iqkwg
Content-Type: application/json

{
  "age": 33,
  "email": "karensmith@gmail.com",
  "name": "Karen Smith",
  "workingPosition": 3
}
